### ISSUE TITLE
Error in Accounts Screen

### ISSUE THREAD

**Issue by jomo-rgs** [jomo-rgs/bills#31]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/jonathanmoore/Documents/Python/bills/bills.py", line 243, in btnEditAccount_event
    account_form.account_form(2)
  File "/Users/jonathanmoore/Documents/Python/bills/account_form.py", line 90, in account_form
    accounts = Accounts(None, None)
  File "/Users/jonathanmoore/Documents/Python/bills/accounts.py", line 16, in __init__
    self._accounts.append(Account(record))
  File "/Users/jonathanmoore/Documents/Python/bills/account.py", line 28, in __init__
    self.set_month(account[3])
  File "/Users/jonathanmoore/Documents/Python/bills/account.py", line 52, in set_month
    self.month = int(x)
ValueError: invalid literal for int() with base 10: ''

**Comment by jomo-rgs** [comment]
Added more explicit code to the set function to handle different type. This was being caused by an empty string. Cannot be converted to an int.

**Comment by jomo-rgs** [comment]
Fixed in Release 0.8.1
